[project]
name = "hello-world"
version = "1.0.0"
description = "My firs python package in se from das in december 2024"
requires-python = ">=3.8"
authors = [
    {name = "John Doe", email = "johndoe@example.com"},
]
dependencies = [
    "numpy",
    "pandas",
]